name: CD
on:
  workflow_dispatch:
defaults:
  run:
    shell: pwsh
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Generate File Hash
        env:
          TEMP: ${{ runner.temp }}
        run: |
          $path = './VenafiPS'
          $fullPath = Resolve-Path $path | Select-Object -ExpandProperty Path
          Get-ChildItem -Path $path -Recurse | Get-FileHash -Algorithm SHA256 | Select-Object Hash, 
          @{
              'n' = 'File'
              'e' = {
                  $_.Path.Replace("$fullPath\", '')
              }
          } | ConvertTo-Json | Out-File -FilePath ../hash.json
          gc ../hash.json -raw
